---
title: "Envisioning Neighborhood Futures After the Chinatown Stitch"
author: "Luming Xu, Sijia Zhang, Aki Di Sandro, Ray Ma, Yixuan Zhou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.show = "asis",
    fig.align = "center") 
options(scipen=999)

library(sf)
library(ggplot2)
```

# Data Wrangling


## Property Data

+ [Philadelphia Properties and Assessment History](https://opendataphilly.org/datasets/philadelphia-properties-and-assessment-history/)

Census Tract 376, 2, 5

```{r}
property <- st_read("data/opa_properties_public.geojson") %>%
  st_transform('EPSG:2272')
```

```{r}
# research <- property %>%
#   dplyr::
```


```{r}
ggplot() +
  geom_sf(data = property, aes(color=sale_price)) +
  theme_void()
```


## Neighborhood Context

+ ACS Census Data:
+ [PPR Properties](https://opendataphilly.org/datasets/ppr-properties/)

## The Stitch

## Third Party Data




# Exploratory Data Analysis

