---
title: "Envisioning Neighborhood Futures After the Chinatown Stitch"
author: "Luming Xu, Sijia Zhang, Aki Di Sandro, Ray Ma, Yixuan Zhou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.show = "asis",
    fig.align = "center") 
options(scipen=999)

library(sf)
library(ggplot2)
library(tidycensus)
library(tidyverse)
library(lwgeom)
library(FNN)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

# Data Wrangling

## Study Area (xlm)

+ [Vine Street Expressway (I-676)](https://opendataphilly.org/datasets/pa-dot-state-roads/)

```{r Luming-studyarea}
studyarea <- st_read("data/StudyArea.shp") %>%
  st_transform('EPSG:2272')

Philly_blockgroup <- st_read("data/Philly_blockgroup.shp") %>%
  st_transform('EPSG:2272')

StateRoads <- st_read("data/PaStateRoads2024_03.geojson") %>%
  st_transform('EPSG:2272') %>%
  st_intersection(st_union(Philly_blockgroup))

Casestudy_Highways <- StateRoads %>%
  filter(TRAF_RT_NO %in% c("I", "US")) %>%
  dplyr::select(STREET_NAM, ST_RT_NO, TRAF_RT_NO, TRAF_RT__1, geometry) %>%
  filter(ST_RT_NO %in% c("0001", "0095", "0076", "0676"))

# st_write(Casestudy_Highways %>% st_transform('EPSG:3857'), "data/Casestudy_Highways.shp", driver = "ESRI Shapefile")

I_676 <- I_Roads %>%
  filter(TRAF_RT__1 == 676)

# st_write(I_676 %>% st_transform('EPSG:3857'), "data/I_676.shp", driver = "ESRI Shapefile")

studyarea_split <- st_split(studyarea, st_union(I_676)) %>%
  st_collection_extract("POLYGON") %>%
  mutate(split_id = row_number())

discontinuity <- studyarea_split %>%
  filter(split_id == 2)

studyarea_north <- studyarea_split %>%
  filter(split_id == 3)

studyarea_south <- studyarea_split %>%
  filter(split_id == 1)

# st_write(discontinuity %>% st_transform('EPSG:3857'), "data/discontinuity.shp", driver = "ESRI Shapefile")
# st_write(studyarea_north %>% st_transform('EPSG:3857'), "data/studyarea_north.shp", driver = "ESRI Shapefile")
# st_write(studyarea_south %>% st_transform('EPSG:3857'), "data/studyarea_south.shp", driver = "ESRI Shapefile")

landuse <- 
  st_read("data/Land_Use_ClipLayer.shp") %>%
  st_transform('EPSG:2272')

Chinatown_Stitch <- landuse %>%
  filter(OBJECTID_1 %in% c(500392, 511294, 511361))

```

```{r}
ggplot() +
  geom_sf(data = StateRoads) +
  geom_sf(data = Casestudy_Highways, color = "red") +
  geom_sf(data = I_676, color = "green") +
  theme_void()
```


## Property Data

+ [Philadelphia Properties and Assessment History](https://opendataphilly.org/datasets/philadelphia-properties-and-assessment-history/)

Census Tract 376, 2, 5

```{r property-studyarea}
property <- st_read("data/opa_properties_public.geojson") %>%
  st_transform('EPSG:2272')

property_studyarea <- st_filter(property, studyarea)
```


```{r}
ggplot() +
  # geom_sf(data = Philly_blockgroup, fill = "transparent", color = "grey") +
  geom_sf(data = property_studyarea, aes(color=sale_price)) +
  theme_void()
```


## Neighborhood Context

+ [PPR Properties](https://opendataphilly.org/datasets/ppr-properties/)
+ [Neighborhoods](https://opendataphilly.org/datasets/philadelphia-neighborhoods/)
+ [Trolley Stations](https://hub.arcgis.com/datasets/dd2afb618d804100867dfe0669383159_0/explore?location=39.956470%2C-75.160382%2C14.19)
+ [Highspeed Stations](https://hub.arcgis.com/datasets/af52d74b872045d0abb4a6bbbb249453_0/explore?location=39.955164%2C-75.153952%2C14.43)
+ [Bike Network](https://opendataphilly.org/datasets/bike-network/)
+ [311 Requests](https://opendataphilly.org/datasets/311-service-and-information-requests/)
+ [Lans use 2023](https://opendataphilly.org/datasets/land-use/)

### Data Wrangling

```{r Luming-DataWrangling}
nhoods <- 
  st_read("data/philadelphia-neighborhoods.geojson") %>%
  st_transform('EPSG:2272')

park <- 
  st_read("https://opendata.arcgis.com/datasets/d52445160ab14380a673e5849203eb64_0.geojson") %>%
  st_transform('EPSG:2272')

metro <- 
  st_read("https://opendata.arcgis.com/api/v3/datasets/af52d74b872045d0abb4a6bbbb249453_0/downloads/data?format=geojson&spatialRefId=4326") %>%
  st_transform('EPSG:2272') %>%
  mutate(Type = "metro")

city_hall <- metro[metro$Station == 'City Hall', 6]

trolley <-
    st_read("https://opendata.arcgis.com/api/v3/datasets/dd2afb618d804100867dfe0669383159_0/downloads/data?format=geojson&spatialRefId=4326") %>%
  st_transform('EPSG:2272')

trolley_renamed <- trolley %>%
  rename(Station = StopName,
         Route = LineAbbr,
         Longitude = Lon,
         Latitude = Lat) %>%
  mutate(Type = "trolley")

# Combine both datasets into one
transit <- bind_rows(metro, trolley_renamed)

school <-
  st_read("https://opendata.arcgis.com/datasets/d46a7e59e2c246c891fbee778759717e_0.geojson") %>%
  st_transform('EPSG:2272')

hospital <-
  st_read("data/DOH_Hospitals202311.geojson") %>%
  st_transform('EPSG:2272') %>%
  st_filter(st_union(Philly_blockgroup))

water <-
  st_read("https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/Hydrographic_Features_Poly/FeatureServer/1/query?outFields=*&where=1%3D1&f=geojson") %>%
  st_transform('EPSG:2272')

bike_network <- 
  st_read("data/Bike_Network.geojson") %>%
  st_transform('EPSG:2272')

phillyCrimes <- 
  st_read("data/phillyCrimes.geojson") %>%
  st_transform('EPSG:2272')

# LPSS_PER1000: Number of low-produce supply stores per 1,000 people
# HPSS_PER1000: Number of high-produce supply stores per 1,000 people
retail <-
  st_read("https://opendata.arcgis.com/datasets/53b8a1c653a74c92b2de23a5d7bf04a0_0.geojson") %>%
  st_transform('EPSG:2272')

```

### Data Processing

```{r Luming-DataWrangling-Property}
landuse_rename <- landuse %>%
  mutate(landuse = 
           case_when(
    C_DIG2DESC == 11 ~ "Residential Low",
    C_DIG2DESC == 12 ~ "Residential Medium",
    C_DIG2DESC == 13 ~ "Residential High",
    C_DIG2DESC == 21 ~ "Commercial Consumer",
    C_DIG2DESC == 22 ~ "Commercial Business/Professional",
    C_DIG2DESC == 23 ~ "Commercial Mixed Residential",
    C_DIG2DESC == 31 ~ "Industrial",
    C_DIG2DESC == 41 ~ "Civic/Institution",
    C_DIG2DESC == 51 ~ "Transportation",
    C_DIG2DESC == 61 ~ "Culture/Amusement",
    C_DIG2DESC == 62 ~ "Active Recreation",
    C_DIG2DESC == 71 ~ "Park/Open Space",
    C_DIG2DESC == 72 ~ "Cemetery",
    C_DIG2DESC == 81 ~ "Water",
    C_DIG2DESC == 91 ~ "Vacant",
    C_DIG2DESC == 92 ~ "Other/Unknown"
  ))

calculate_nearest_distance <- function(set_points, other_layer) {
  nearest_idx <- st_nearest_feature(set_points, other_layer)
  st_distance(set_points, other_layer[nearest_idx, ], by_element = TRUE) %>% as.numeric()
}

Luming_property <- property_studyarea %>%
  dplyr::select(objectid, geometry)

Luming_property <- Luming_property %>%
  mutate(distance_to_city_hall = st_distance(., city_hall) %>% as.numeric()) %>%
  mutate(
    distance_to_nearest_transit = calculate_nearest_distance(geometry, transit),
    distance_to_nearest_hospital = calculate_nearest_distance(geometry, hospital),
    distance_to_nearest_school = calculate_nearest_distance(geometry, school),
    distance_to_nearest_park = calculate_nearest_distance(geometry, park),
    distance_to_nearest_water = calculate_nearest_distance(geometry, water),
    distance_to_nearest_bikelane = calculate_nearest_distance(geometry, bike_network),
    distance_to_I676 = calculate_nearest_distance(geometry, I_676)
  ) %>%
  st_join(nhoods["NAME"]) %>%
  rename(nhoods_name = NAME) %>%
  st_join(landuse_rename["landuse"]) %>%
  st_join(retail[, c("LPSS_PER1000", "HPSS_PER1000")])

Luming_property <- Luming_property %>% 
    mutate(
      crime_nn1 = nn_function(st_coordinates(Luming_property),
                              st_coordinates(phillyCrimes), k = 1),

      crime_nn2 = nn_function(st_coordinates(Luming_property),
                              st_coordinates(phillyCrimes), k = 2),

      crime_nn3 = nn_function(st_coordinates(Luming_property),
                              st_coordinates(phillyCrimes), k = 3),

      crime_nn4 = nn_function(st_coordinates(Luming_property),
                              st_coordinates(phillyCrimes), k = 4),
      
      crime_nn5 = nn_function(st_coordinates(Luming_property), 
                              st_coordinates(phillyCrimes), k = 5))

# Save as CSV
# write.csv(st_drop_geometry(Luming_property), "data/Luming_property.csv", row.names = FALSE)
```

## Park changed

```{r}
park <- st_read("E:/Spring/Practicum/DataAnalysis/Chinatown/Dataset/ParksModified/Parks_within_1km.shp") %>%
  st_transform('EPSG:2272')

property_park <- property_studyarea %>%
  dplyr::select(objectid, geometry) %>%
  mutate(distance_to_nearest_park = calculate_nearest_distance(geometry, park))

st_write(property_park, "data/property_park.geojson")
```



## Census Data

```{r}
census_api_key("e62580f74ef222beadd9dd2fbaf48ff130b31c4a", overwrite = TRUE)
acs_variable_list.2023 <- load_variables(2023, #year
                                         "acs5", #five year ACS estimates
                                         cache = TRUE)
```

```{r}
tracts23 <- get_acs(geography = "block group",
                    variables = c("B01003_001E", "B01001A_001E","B06011_001E"), 
                    year=2023, 
                    state=42, 
                    county=101, 
                    geometry=FALSE, 
                    output="wide") %>%
  # st_transform('EPSG:2272') %>%
  rename(TotalPop = B01003_001E, 
         TotalWhites = B01001A_001E,
         MedInc = B06011_001E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(year = "2023",
         percentWhite = TotalWhites / TotalPop,
         raceContext = ifelse(percentWhite > .5, "Majority White", "Majority Non-White"),
         incomeContext = ifelse(MedInc > mean(MedInc, na.rm = T), "High Income", "Low Income"))
```

## Third Party Data




# Exploratory Data Analysis

