---
title: 'EDA: Discontinuity Effects'
author: "Luming Xu"
date: "`r Sys.Date()`"
output:
    html_document:
      code_folding: hide
---

```{r setup, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.show = "asis",
    fig.align = "center")
knitr::opts_knit$set(root.dir = "E:/Spring/Practicum/DataAnalysis/Chinatown")

library(sf)
library(ggplot2)
library(tidycensus)
library(tidyverse)
library(ggtext)
library(glue)
library(leaflet)
library(mapview)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

# Data Processing

```{r quiet = TRUE, results = 'hide'}
property_EDA <- st_read("Dataset/property_sijia_eda.geojson") %>%
  st_transform('EPSG:2272')

I_676 <- st_read("Dataset/Highways/I_676.shp") %>%
  st_transform('EPSG:2272')

studyarea_north <- st_read("Dataset/studyarea-sub/studyarea_north.shp") %>%
  st_transform('EPSG:2272')

studyarea_south <- st_read("Dataset/studyarea-sub/studyarea_south.shp") %>%
  st_transform('EPSG:2272')

```

```{r}
property_highway <- 
  rbind(
    property_EDA %>% st_intersection(studyarea_north["geometry"]) %>%
      mutate(I676 = "north"),
    property_EDA %>% st_intersection(studyarea_south["geometry"]) %>%
      mutate(I676 = "south")
  )

property_highway_distance <- property_highway %>%
  mutate(distance_to_highway = case_when(
    I676 == "north" ~ distance_to_I676,
    I676 == "south" ~ -distance_to_I676
  ))

property_summary <- property_highway_distance %>%
  st_drop_geometry() %>%
  group_by(distance_to_highway, I676) %>%
  summarise(sale_price.x = mean(sale_price.x, na.rm = TRUE), .groups = "drop")

property_summary_plot <- property_summary %>%
  filter(sale_price.x > 10 & sale_price.x < 1e6)
```

```{r}
ggplot(property_summary_plot, aes(x = sale_price.x)) +
  geom_histogram(bins = 30, fill = "#6D9EC1", color = "black", alpha = 0.5) +
  labs(title = "Distribution of Sale Price") +
  theme_minimal()
```

# Discontinuity Effects

local regression line

This ‘boundary discontinuity’ plot highlights how the sale-price conditions change on either immediate side of the I-676.

```{r}
ggplot(property_summary_plot, aes(x = distance_to_highway, y = sale_price.x, color = I676)) +
  geom_point(size = 0.5) +
  geom_smooth(method = "loess", se = FALSE, size = 1.2) +
  geom_vline(xintercept = 0, color = "black", size = 2) +
  scale_colour_manual(values = c("#eb5600", "#1a9988")) +
  theme_minimal() +
  theme(legend.position = "None",
        plot.title = element_text(size = 18, face = "bold"),
        plot.subtitle = ggtext::element_markdown(size = 12),
        plot.caption = element_text(hjust = 0)) +
  labs(title = 'Sale Price as a Function of Distance to the Highway', 
       subtitle = glue("<span style='color:#1a9988;'>South Side</span> vs. <span style='color:#eb5600;'>North Side</span>"),
       # caption = "Figure 4.1",
       # x = "South Side of the Highway          I-676                                     North Side of the Highway",
       x = "Distance to the Highyway (ft)                          ",
       y = "Sale Price ($)") +
    geom_label(aes(x = 0, y = 750000,
                 label = "I-676"),
             fill = "black", color = "white", fontface = "bold", size = 5)

  # theme(
  #   legend.position = "None",
  #   plot.title = element_text(face = "bold", size = 18),
  #   plot.caption = element_markdown(size = 12)
  # ) +
  # # Manually adding colored text for x-axis labels
  # annotate("text", x = min(property_summary_plot$distance_to_highway), y = 750000, 
  #          label = "South Side", color = "#1a9988", size = 5, hjust = 0) +
  # annotate("text", x = max(property_summary_plot$distance_to_highway), y = 750000, 
  #          label = "North Side", color = "#eb5600", size = 5, hjust = 1) +


```

# Case Study (for Aki)

```{r quiet = TRUE, results = 'hide'}
prop500 <- st_read("Dataset/phl_properties_dist2highway/philly_prop500_dist2highway.geojson") %>%
  st_transform('EPSG:2272')

prop500_plot <- prop500 %>%
  filter(sale_price > 10 & sale_price < 1e6)
```

```{r}
ggplot(data = prop500_plot, 
       aes(x = dist_to_closest_highway, y = sale_price, 
           color = closest_highway, fill = closest_highway)) +
  geom_point(alpha = .1, size = 0.3) +
  geom_smooth(method = "loess", se = FALSE, size = 1.2) +
  scale_color_manual(values = c("US-1" = "red",
                                "I-76" = "blue",
                                "I-95" = "purple",
                                "I-676" = "pink")) +
  scale_fill_manual(values = c("US-1" = "red",
                               "I-76" = "blue",
                               "I-95" = "purple",
                               "I-676" = "pink")) +
  labs(title = "Property Price as a function of Distance to Closest Highway",
       subtitle = "Colored by Closest Highway; Properties within 500m of highways",
       fill = "Closest Highway",
       color = "Closest Highway") +
  theme_minimal()
```

```{r}
cor <- prop500_plot %>%
  st_drop_geometry() %>%
  group_by(closest_highway) %>%
  summarize(correlation = cor(dist_to_closest_highway, log_price_perTA, method = "pearson"), .groups = "drop")
cor
```

```{r}
# simple scatter of price (as log price per total area in sq ft) and dist2closesthighway
ggplot(data = prop500_plot, 
       aes(x = dist_to_closest_highway, y = log_price_perTA, 
           color = closest_highway, fill = closest_highway)) +
  geom_point(alpha = .1, size = 0.3) +
  geom_smooth(method = "lm", se=F, size = 1.2) +
  scale_color_manual(values = c("US-1" = "red",
                                "I-76" = "blue",
                                "I-95" = "purple",
                                "I-676" = "pink")) +
  scale_fill_manual(values = c("US-1" = "red",
                               "I-76" = "blue",
                               "I-95" = "purple",
                               "I-676" = "pink")) +
  labs(title = "Property Price (log price per TA) as a function of Distance to Closest Highway",
       subtitle = "Colored by Closest Highway; Properties within 500m of highways",
       fill = "Closest Highway",
       color = "Closest Highway") +
  theme_minimal()
```

# Use Case

```{r quiet = TRUE, results = 'hide'}
studyarea <- st_read("Dataset/studyarea/StudyArea.shp") %>%
  st_transform('EPSG:2272')

studyarea_4326 <- st_transform(studyarea, crs = 4326)
bbox <- as.list(st_bbox(studyarea_4326))

ChinatownStitch_4326 <- st_read("Dataset/Chinatown_Stitch/Chinatown_Stitch.shp") %>%
  st_transform('EPSG:4326')

I676_4326 <- st_transform(I_676, crs = 4326)

landuse_4326 <- st_read("Dataset/landuse_clip/Land_Use_ClipLayer.shp") %>%
  st_transform('EPSG:4326')

landuse_4326_plot <- landuse_4326 %>%
  filter(C_DIG2DESC != 51 & C_DIG2DESC != 71)

landuse_park <- landuse_4326 %>%
  filter(C_DIG2DESC == 71)

landuse_park_ing <- landuse_4326 %>%
  filter(OBJECTID_1 == 514214)

nhoods_4326 <- 
  st_read("DataWrangling/data/philadelphia-neighborhoods.geojson") %>%
  st_transform('EPSG:4326')

Chinatown_Callowhill <- nhoods_4326 %>%
  filter(NAME %in% c("CHINATOWN", "CALLOWHILL"))
```


```{r}
UseCase <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = studyarea_4326,
              color = "black",       # Black border
              weight = 4,            # Border thickness
              dashArray = "8,12",     # Dashed line pattern (5px on, 5px off)
              fill = FALSE) %>%
    addPolygons(data = landuse_4326_plot,
              color = "grey",
              weight = 0.8,
              fillColor = "#DFF3E3",
              fillOpacity = 0.4) %>%
  addPolygons(data = Chinatown_Callowhill,
              color = "#eb5600",
              weight = 1,
              opacity = 0.5,
              dashArray = "5,5",
              fillColor = "#eb5600",
              fillOpacity = 0.1) %>%
  addPolygons(data = landuse_park,
              color = "#1a9988",
              weight = 1,
              fillOpacity = 0.6,
              fillColor = "#1a9988") %>%
  addPolygons(data = landuse_park_ing,
              color = "#1a9988",
              weight = 2,
              opacity = 0.8,
              fill = FALSE) %>%
  addPolylines(data = I676_4326,
               color = "#eb5600",
               opacity = 1,
               weight = 2) %>%
  addPolygons(data = ChinatownStitch_4326,
              color = "#eb5600",
              weight = 2,
              opacity = 1,
              fillColor = "#1a9988",
              fillOpacity = 0.8
              # fill = alpha("#1a9988", 0.5)
              ) %>%
  fitBounds(
    lng1 = bbox$xmin, 
    lat1 = bbox$ymin, 
    lng2 = bbox$xmax, 
    lat2 = bbox$ymax
  )
UseCase
```


# Basic Geography: potential lands

```{r quiet = TRUE, results = 'hide'}
landuse <- st_read("Dataset/landuse_clip/Land_Use_ClipLayer.shp") %>%
  st_transform('EPSG:2272')

discontinuity <- st_read("Dataset/studyarea-sub/discontinuity.shp") %>%
  st_transform('EPSG:2272')

Chinatown_Stitch <- st_read("Dataset/Chinatown_Stitch/Chinatown_Stitch.shp") %>%
  st_transform('EPSG:2272')

property_vacant <- property_EDA %>%
  filter(category_code_description %in% c("VACANT LAND","SINGLE FAMILY", "VACANT LAND - NON-RESIDENTIAL")) %>%
  mutate(category_code_description = case_when(
    category_code_description == "VACANT LAND - NON-RESIDENTIAL" ~ "VACANT LAND",
    TRUE ~ category_code_description
  ))
```

```{r}
ggplot() +
  geom_sf(data = landuse, fill = "white", color = "gray85", size = 0.05) +
  geom_sf(data = studyarea, fill = "transparent", color = "grey", linetype = "dashed", linewidth = 2) +
  geom_sf(data = discontinuity, fill = "#eb5600", color = "transparent") +
  geom_sf(data = Chinatown_Stitch, fill = "#1a9988", alpha = 0.8) +
  geom_sf(data = property_vacant, aes(color = category_code_description), size = 1) +
  scale_colour_manual(values = c("black", "#B67352")) +
  labs(title="Potential Lands",
       subtitle = glue("<span style='color:#1a1a1a;'>Single Family & </span><span style='color:#B67352;'>Vacant Land</span>"),
       # caption = "Figure "
       ) +
  theme_void() +
  theme(legend.position = "none",
        plot.title = element_text(size = 18, face = "bold"),
        plot.subtitle = ggtext::element_markdown(size = 12))
```

