---
title: "Feature Engineering Section"
author: "Sijia"
date: '2025-03-08'
output:
    html_document:
      code_folding: hide
---

```{r setup, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.show = "asis",
    fig.align = "center")
knitr::opts_knit$set(root.dir = "~/Documents/Upenn/Practicum/2025/results")

palette5 <- colorRampPalette(c("#1a9988", "#eb5600"))(5)
library(ggplot2)
library(tidyverse)
library(sf)
library(dplyr)
library(tidyr)
library(rlang)
library(patchwork)
```

### Data Set up
```text
1.  property_CT <- Property -  Chinatown scale - with FE
2.  property_final <- Property - Chinatown scale - without FE
2.  Third party: POIs (added in the property dataset)
```   
```{r Data set up, quiet = TRUE, results = 'hide'}
property_final <- st_read("~/Documents/Upenn/Practicum/2025/Chinatown-Practicum/DataWrangling/property_final.geojson") %>%
  st_transform('EPSG:2272')
```

### Features
```text
1. Log Distance to Restaurant
2. Log Distance to grocery
3. Features in Property Data
  a. Internal Features
    - interior condition 
    - number of bathrooms 
    - number of bedrooms 
    - separate_utilities 

  b. External Features
    - years built 
    - exterior condition 
    - quality grade 
    - central air 
    - garage spaces 
    - general condition 
    - building code description
    
  c. Spatial characteristics
    - depth
    - zoning 
    - distances related features
```
### Third Party Data 
```{r POI, quiet = TRUE, results = 'hide'}
### POI-restaurant-drink-dessert

api_key <- ""
keywords <- c("restaurant", "dim sum restaurant", "kitchen", "desert","tea", "bubble tea",  "matcha", "chai", "herbal tea")
place_types <- c("restaurant", "cafe", "bakery")

studyarea_proj <- st_transform(block2023_studyarea, 2272)

grid_pts <- st_make_grid(studyarea_proj, cellsize = 2000, what = "centers")
grid_pts <- st_sf(geometry = grid_pts) %>%
  st_filter(st_buffer(studyarea_proj, 1000)) 

grid_pts_wgs <- st_transform(grid_pts, 4326)
coords <- st_coordinates(grid_pts_wgs)

all_responses <- list()

for (pt_idx in seq_len(nrow(coords))) {
  location <- coords[pt_idx, c(2,1)]  # lat, lng
  cat(" Querying center point", pt_idx, "at", paste(location, collapse = ", "), "\n")
  
  for (ptype in place_types) {
    for (kw in keywords) {
      Sys.sleep(5)  
      cat("🔎", kw, "in", ptype, "\n")

      response <- google_places(
        keyword = kw,
        location = location,
        radius = 2000,  
        place_type = ptype,
        key = api_key
      )

      if (is.null(response[["results"]]) || length(response[["results"]]) == 0) {
        cat("No results for:", kw, "in", ptype, "\n")
        next
      }

      page_token <- response$next_page_token
      results_list <- list(response[["results"]])
      i <- 1

      while (!is.null(page_token)) {
        Sys.sleep(10)
        response_next <- google_places(
          keyword = kw,
          location = location,
          radius = 2000,
          place_type = ptype,
          key = api_key,
          page_token = page_token
        )

        if (is.null(response_next[["results"]]) || length(response_next[["results"]]) == 0) break

        results_list[[i + 1]] <- response_next[["results"]]
        page_token <- response_next$next_page_token
        i <- i + 1
      }

      all_responses[[paste(kw, ptype, pt_idx, sep = "_")]] <- bind_rows(results_list) %>%
        filter(!is.na(place_id)) %>%
        distinct(place_id, .keep_all = TRUE)
    }
  }
}

all_responses <- all_responses[lengths(all_responses) > 0]
restaurant_results <- bind_rows(all_responses) %>%
  mutate(lat = geometry$location$lat, lng = geometry$location$lng) %>%
  select(lat, lng, name, place_id, rating) %>%
  distinct(place_id, .keep_all = TRUE)

restaurant_sf <- st_as_sf(restaurant_results, coords = c("lng", "lat"), crs = 4326)
restaurant_proj <- st_transform(restaurant_sf, 2272)

studyarea_buffer <- st_buffer(studyarea_proj, 2000)
res_poi <- st_filter(restaurant_proj, studyarea_buffer)
radius_circles <- st_buffer(st_transform(grid_pts, 2272), dist = 2000)

### POI - grocery
keywords <- c("grocery store", "supermarket", "asian grocery", "chinese supermarket",
              "korean market", "japanese grocery", "international market", "food market")

place_types <- c("supermarket", "grocery_or_supermarket", "convenience_store", "store")

studyarea_proj <- st_transform(block2023_studyarea, 2272)

grid_pts <- st_make_grid(studyarea_proj, cellsize = 2000, what = "centers")
grid_pts <- st_sf(geometry = grid_pts) %>%
  st_filter(st_buffer(studyarea_proj, 1000))

grid_pts_wgs <- st_transform(grid_pts, 4326)
coords <- st_coordinates(grid_pts_wgs)

all_responses <- list()

for (pt_idx in seq_len(nrow(coords))) {
  location <- coords[pt_idx, c(2,1)]  # lat, lng
  cat(" Querying center", pt_idx, "at", paste(location, collapse = ", "), "\n")
  
  for (ptype in place_types) {
    for (kw in keywords) {
      Sys.sleep(5)  
      cat("🔎", kw, "in", ptype, "\n")

      response <- google_places(
        keyword = kw,
        location = location,
        radius = 2000,
        place_type = ptype,
        key = api_key
      )

      if (is.null(response[["results"]]) || length(response[["results"]]) == 0) next

      page_token <- response$next_page_token
      results_list <- list(response[["results"]])
      i <- 1

      while (!is.null(page_token)) {
        Sys.sleep(10)
        response_next <- google_places(
          keyword = kw,
          location = location,
          radius = 2000,
          place_type = ptype,
          key = api_key,
          page_token = page_token
        )
        if (is.null(response_next[["results"]]) || length(response_next[["results"]]) == 0) break

        results_list[[i + 1]] <- response_next[["results"]]
        page_token <- response_next$next_page_token
        i <- i + 1
      }

      all_responses[[paste(kw, ptype, pt_idx, sep = "_")]] <- bind_rows(results_list) %>%
        filter(!is.na(place_id)) %>%
        distinct(place_id, .keep_all = TRUE)
    }
  }
}

all_responses <- all_responses[lengths(all_responses) > 0]

grocery_results <- bind_rows(all_responses) %>%
  mutate(lat = geometry$location$lat,
         lng = geometry$location$lng) %>%
  select(lat, lng, name, place_id, rating) %>%
  distinct(place_id, .keep_all = TRUE)

grocery_sf <- st_as_sf(grocery_results, coords = c("lng", "lat"), crs = 4326)
grocery_proj <- st_transform(grocery_sf, 2272)

studyarea_buffer <- st_buffer(studyarea_proj, 2000)
grocery <- st_filter(grocery_proj, studyarea_buffer)

### property join poi

property_sf <- st_as_sf(property_combined, sf_column_name = "geometry")
property_proj <- st_transform(property_sf, 2272)
grocery_proj <- st_transform(grocery, 2272)
restaurant_proj <- st_transform(res_poi, 2272)

grocery_idx <- st_nearest_feature(property_proj, grocery_proj)

property_proj$nearest_grocery_name <- grocery_proj$name[grocery_idx]
property_proj$nearest_grocery_dist <- st_distance(
  property_proj,
  grocery_proj[grocery_idx, ],
  by_element = TRUE
)

restaurant_idx <- st_nearest_feature(property_proj, restaurant_proj)

property_proj$nearest_restaurant_name <- restaurant_proj$name[restaurant_idx]
property_proj$nearest_restaurant_dist <- st_distance(
  property_proj,
  restaurant_proj[restaurant_idx, ],
  by_element = TRUE
)

property_proj$nearest_grocery_dist_m <- as.numeric(property_proj$nearest_grocery_dist)
property_proj$nearest_restaurant_dist_m <- as.numeric(property_proj$nearest_restaurant_dist)

clean_property_poi_distances <- function(property_sf) {
  property_sf %>%
    mutate(
      nearest_grocery_dist_m = as.numeric(nearest_grocery_dist),
      nearest_restaurant_dist_m = as.numeric(nearest_restaurant_dist)) %>%
    select(
      -nearest_grocery_dist,
      -nearest_restaurant_dist
    )
}
property_final <- clean_property_poi_distances(property_proj)
#st_write(property_final, "property_final.geojson", driver = "GeoJSON", delete_dsn = TRUE)
```


### Feature Engineering
```{r FE countinued}
property_CT <- property_final %>%
  mutate(
    year_built = as.numeric(year_built),
    year_built_group = case_when(
    year_built < 1990 ~ "Before 1990",
    year_built >= 1990 & year_built < 2000 ~ "1940-1979",
    year_built >= 2000 & year_built < 2020 ~ "1980s-1990s",
#    year_built >= 2010 & year_built < 2020 ~ "2000s-2010s",
    year_built >= 2020 ~ "2010s+"),
    log_price = log(adj_sale_price),
    log_dist_highway = log(distance_to_I676 +1),
    
    central_air = case_when(
      central_air %in% c("1", "0","N","Y") ~ "Y",  
      TRUE ~ "N"                          
    ),
    central_air = factor(central_air),
    
    exterior_condition_recode = case_when(
      is.na(exterior_condition) | exterior_condition == 2 ~ "Good",
      exterior_condition %in% c(1, 6, 7) ~ "Average",
      exterior_condition %in% c(3, 4, 5) ~ "Poor"
    ),

    exterior_condition = factor(exterior_condition),
  
    interior_condition_recode = case_when(
      interior_condition %in% c(2, NA) ~ "Good",
      interior_condition %in% c(1,4,6)~ "Average",
      interior_condition %in% c(3,5,7) ~ "Poor"
    ),
    interior_condition = factor(interior_condition),
    
    garage_spaces = case_when(
      is.na(garage_spaces) | garage_spaces == 0 ~ "0",    
      garage_spaces == 1 ~ "1",      
      TRUE ~ "2"                     
    ),
    garage_spaces = factor(garage_spaces),
    
    general_construction = case_when(       
      general_construction %in% c("A ", "B ", "D ") ~ "A",  
      general_construction == "3 " ~ "C",        
      TRUE ~ "B"                                 
    ),
    general_construction = factor(general_construction),
    
    number_of_bathrooms = case_when(
      number_of_bathrooms == 0 ~ "0",                   
      number_of_bathrooms == 1 ~ "1",                   
      number_of_bathrooms %in% c(2, NA) ~ "2",          
      number_of_bathrooms == 3 ~ "3",                   
      TRUE ~ "4"                                        
    ),
    number_of_bathrooms = factor(number_of_bathrooms),
    
    number_of_bedrooms = case_when(
      number_of_bedrooms %in% c(0, 12) | is.na(number_of_bedrooms) ~ "0",  
      number_of_bedrooms %in% c(1, 2) ~ "1",    
      number_of_bedrooms == 3 ~ "2",            
      number_of_bedrooms == 4 ~ "3",            
      number_of_bedrooms %in% c(5, 6) ~ "4",    
      number_of_bedrooms %in% c(7, 8, 9) ~ "5" 
    ),
    number_of_bedrooms = factor(number_of_bedrooms),
    
    
    quality_grade_recode = case_when(
      quality_grade %in% c("A+", "A") ~ "1", 
      quality_grade %in% c("A-","3", "7") ~ "2", 
      TRUE ~ "3"
    ),
    quality_grade = factor(quality_grade),
    
    separate_utilities = case_when(
      separate_utilities %in% c("A", "C") ~ "B",  
      TRUE ~ "A"                                 
    ),
    separate_utilities = factor(separate_utilities),
    
    
    building_code_description_new = case_when(
      building_code_description_new %in% c("COLONIAL", "OLD STYLE", "ROW MODERN", "ROW OLD STYLE", "TUDOR", "TWIN BUNGALOW") ~ "1",
      building_code_description_new %in% c("ROW POST WAR", "ROW TYPICAL", "TWIN CONVENTIONAL") ~ "3",
      building_code_description_new %in% c("OTHER", "ROW PORCH FRONT") ~ "4",
      TRUE ~ "2"
    ),
    building_code_description_new = factor(building_code_description_new),

    zoning_group = case_when(
    zoning %in% c("CMX5") ~ "CMX5",
    zoning %in% c("IRMX") ~ "IRMX",
    zoning %in% c("RM1","RM2", "RM4") ~ "RM",
    zoning %in% c("RMX3") ~ "RMX3",
    zoning %in% c("RSA5") ~ "RSA5",
    zoning %in% c("ICMX") ~ "ICMX",
    zoning %in% c("SPPOA") ~ "SPPOA",
    zoning %in% c("I2") ~ "I2",
    zoning %in% c("CMX2.5", "CMX2", "CMX1") ~ "CMX(1,2,2.5)",
    zoning %in% c("CMX3", "CMX4") ~ "CMX(3,4)",
    TRUE ~ "Other"),
  zoning_group = factor(zoning_group)

  )

mean_depth <- mean(property_CT$depth, na.rm = TRUE)
property_CT$depth[is.na(property_CT$depth)] <- mean_depth

```

